### PR TITLE
Fixes for Swift Package Manager #47

### PR DESCRIPTION
**Pull request by kenji21**
see issue https://github.com/AladinWay/TransitionButton/issues/47 and comment this comment : https://github.com/AladinWay/TransitionButton/issues/47#issuecomment-730203695

### CODE REVIEW

**Comment by JMCPH** [comment]
@AladinWay what is the status on this? I keep getting this SPM error:
```
Showing All Messages
the manifest is missing a Swift tools version specification; consider prepending to the manifest '// swift-tools-version:5.4.0' to specify the current Swift toolchain version as the lowest Swift version supported by the project; if such a specification already exists, consider moving it to the top of the manifest, or prepending it with '//' to help Swift Package Manager find it

```

**Comment by JMCPH** [comment]
@AladinWay sorry for the tag, but would you mind looking at this?

**Comment by nadimalam** [comment]
Please can someone fix this so that it can become usable again?

@AladinWay are you still working on this or has it been abandoned?

**Comment by JMCPH** [comment]
@nadimalam it's already fixed in the PR, we just need @AladinWay to approve the PR 😅

**Pull request merged**
